services:
  # ┌──────────────────────────────────────────────────────────────┐
  # │ PHP-Composer as service, available in app service            │
  # └──────────────────────────────────────────────────────────────┘
  composer:
    container_name: ${APP_NAME}-app-composer
    image: composer:latest
    restart: always
    volumes:
      - composer:/tmp
    command: /bin/bash -c "/bin/cp /usr/bin/composer /tmp && /bin/cp /usr/bin/composer /tmp/c && chmod -R 777 /tmp && sleep 100000"
  # ┌──────────────────────────────────────────────────────────────┐
  # │ Nginx as entry point & proxy to app service                  │
  # └──────────────────────────────────────────────────────────────┘
  app-api:
    container_name: ${APP_NAME}-app-api
    image: nginx
    restart: always
    depends_on:
      - app
    volumes:
      - ./app-api/.docker/nginx/conf.d/default.template.conf:/etc/nginx/conf.d/default.template
      - ./selfsigned.crt:/etc/ssl/selfsigned/selfsigned-crt
      - ./selfsigned.key:/etc/ssl/selfsigned/selfsigned-key
      - ./app:/app
    environment:
      APP_NAME: ${APP_NAME}
    networks:
      @PROJECT_NAME@:
        ipv4_address: 10.120.@S_NET@.2
    command: /bin/bash -c "envsubst '$${APP_NAME}' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    extra_hosts:
      - "app:10.120.@S_NET@.3"
  # ┌──────────────────────────────────────────────────────────────┐
  # │ PHP-Backend app service                                      │
  # └──────────────────────────────────────────────────────────────┘
  app:
    container_name: ${APP_NAME}-app
    build:
      context: ./app/.docker
      target: base
    restart: always
    depends_on:
      - db
      - composer
    volumes:
      - composer:/composer:rw
      - ./app:/app
      - .git:/app/.git
      - ./app/.docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    environment:
      APP_NAME: ${APP_NAME}
      APP_ENV: "dev"
      #      APP_ENV: "prod"
      COMPOSER_PROCESS_TIMEOUT: 7200
      COMPOSER_ALLOW_SUPERUSER: "1"
      COMPOSER_AUTH: '{ "gitlab-token":{ "gitlab.com": "$ACCESS_TOKEN_PAPI_CLIENT" } }'
      PATH: "$PATH:/composer"
      COMPOSER_HOME: "/composer"
      XDEBUG_CONFIG: "remote_host=10.120.@S_NET@.3"
      PHP_IDE_CONFIG: "serverName=@PROJECT_NAME@-docker"
    networks:
      @PROJECT_NAME@:
         ipv4_address: 10.120.@S_NET@.3
    extra_hosts:
      - "@PROJECT_NAME@-db:10.120.@S_NET@.4"
  # ┌──────────────────────────────────────────────────────────────┐
  # │ MariaDB service db                                           │
  # └──────────────────────────────────────────────────────────────┘
  db:
    container_name: ${APP_NAME}-db
    ports:
      - ${DBPORT}:3306
    volumes:
      - .docker/db/config-file.cnf:/etc/mysql/conf.d/config-file.cnf
      - db-data:/var/lib/mysql
    build:
      context: .docker/db
    networks:
      @PROJECT_NAME@:
        ipv4_address: 10.120.@S_NET@.4
    environment:
      MYSQL_ROOT_PASSWORD: root
  # ┌──────────────────────────────────────────────────────────────┐
  # │ Frontend React service web                                   │
  # └──────────────────────────────────────────────────────────────┘
  web:
    container_name: ${APP_NAME}-web
    build:
      context: web/.docker
      target: dev #see in Dockerfile target
    volumes:
      - ./web:/web
      - ./selfsigned.crt:/selfsigned.crt
      - ./selfsigned.key:/selfsigned.key
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - APP_NAME=${APP_NAME}
      - GOOGLECLIENTID=${GOOGLECLIENTID}
      - WEBAPP_ID=${WEBAPP_ID}
      - AUTH_TOKEN_AWARE_URL=${AUTH_TOKEN_AWARE_URL}
    networks:
      @PROJECT_NAME@:
        ipv4_address: 10.120.@S_NET@.5
  # ┌──────────────────────────────────────────────────────────────┐
  # │ Mailer service for testing purpose. Uncomment if needed.     │
  # └──────────────────────────────────────────────────────────────┘
#  mail:
#    image: schickling/mailcatcher
#    container_name: ${APP_NAME}-mail
#    networks:
#      @PROJECT_NAME@:
#        ipv4_address: 10.120.@S_NET@.6
#    environment:
#      - VIRTUAL_HOST=${APP_NAME}-mail
#      - VIRTUAL_PORT=1080
  # ┌──────────────────────────────────────────────────────────────┐
  # │ Schleupen MSSQL service uncomment if needed.                 │
  # └──────────────────────────────────────────────────────────────┘
#  schleupen:
#    container_name: ${APP_NAME}-schleupen
#    build:
#      context: .docker/schleupen
#    environment:
#      - ACCEPT_EULA=Y
#      - SA_PASSWORD=P4ssword
#      - MSSQL_PID=Standard
#    ports:
#      - "1433:1433"
#    volumes:
#      - schleupen-db-data:/var/opt/mssql
#      - .docker/schleupen/init:/schleupen-init
#    networks:
#      @PROJECT_NAME@:
#         ipv4_address: 10.120.@S_NET@.7

# Docker will create volume under /var/lib/docker/volumes
volumes:
  composer: { }
  db-data: {}
#  schleupen-db-data: {}

networks:
  @PROJECT_NAME@:
    name: @PROJECT_NAME@
    driver: bridge
    ipam:
      config:
        - subnet: 10.120.@S_NET@.0/24

# Next lines please add to /etc/hosts file

# 10.120.@S_NET@.2 @PROJECT_NAME@-app.com
# 10.120.@S_NET@.4 @PROJECT_NAME@-db
# 10.120.@S_NET@.5 @PROJECT_NAME@-web.com

# 10.120.@S_NET@.6 @PROJECT_NAME@-mail
# 10.120.@S_NET@.7 @PROJECT_NAME@-schleupen
