services:
  app:
    container_name: @PROJECT_NAME@-app
    build:
      context: app/.docker
      args:
        - APPUID=${APPUID}
        - APPUGID=${APPUGID}
    depends_on:
      - db
    ports:
      - ${APPPORT}:80
    volumes:
      - ./app:/app
      - .git:/app/.git
      - ./app/.docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    networks:
      @PROJECT_NAME@:
        ipv4_address: 10.120.@S_NET@.2
    environment:
      APP_ENV: "dev"
#      APP_ENV: "prod"
      XDEBUG_CONFIG: "remote_host=10.120.@S_NET@.2"
      PHP_IDE_CONFIG: "serverName=@PROJECT_NAME@-docker"
    extra_hosts:
      - "@PROJECT_NAME@-db:10.120.@S_NET@.3"
  db:
    ports:
      - ${DBPORT}:3306
    container_name: @PROJECT_NAME@-db
    volumes:
      - .docker/db/config-file.cnf:/etc/mysql/conf.d/config-file.cnf
      - db-data:/var/lib/mysql
    build:
      context: .docker/db
    networks:
      @PROJECT_NAME@:
        ipv4_address: 10.120.@S_NET@.3
    environment:
      MYSQL_ROOT_PASSWORD: root
  web:
    container_name: @PROJECT_NAME@-web
    build:
      context: web/.docker
      target: dev #see in Dockerfile target
    volumes:
      - ./web:/web
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    networks:
      @PROJECT_NAME@:
        ipv4_address: 10.200.@S_NET@.4
#  mail:
#    image: schickling/mailcatcher
#    container_name: @PROJECT_NAME@-mail
#    networks:
#      @PROJECT_NAME@:
#        ipv4_address: 10.120.@S_NET@.5
#    environment:
#      - VIRTUAL_HOST=@PROJECT_NAME@-mail
#      - VIRTUAL_PORT=1080
volumes:
  db-data: {} # docker will create volume under /var/lib/docker/volumes

networks:
  @PROJECT_NAME@:
    name: @PROJECT_NAME@
    driver: bridge
    ipam:
      config:
        - subnet: 10.120.@S_NET@.0/24

# Entries should be placed in file /etc/hosts
# please add to /etc/hosts file

# 10.120.@S_NET@.2 @PROJECT_NAME@-app
# 10.120.@S_NET@.2 @PROJECT_NAME@-app.com

# 10.120.@S_NET@.3 @PROJECT_NAME@-db

# 10.120.@S_NET@.4 @PROJECT_NAME@-web
# 10.120.@S_NET@.4 @PROJECT_NAME@-web.com

# 10.120.@S_NET@.5 @PROJECT_NAME@-mail
