{
  "name": "@PROJECT_NAME@/webapp-restapi",
  "description": "@PROJECT_NAME@ Rest API Application",
  "version": "0.1.0",
  "license": "MIT",
  "type": "project",
  "minimum-stability": "dev",
  "prefer-stable": true,
  "config": {
    "optimize-autoloader": true,
    "apcu-autoloader": true,
    "discard-changes": true,
    "preferred-install": "dist",
    "sort-packages": true,
    "allow-plugins": {
      "dealerdirect/phpcodesniffer-composer-installer": true,
      "phpstan/extension-installer": true,
      "ajgl/composer-symlinker": true,
      "wikimedia/composer-merge-plugin": true
    }
  },
  "repositories": [
    {
      "type": "vcs",
      "url": "https://github.com/waglpz/http"
    }
  ],
  "require": {
    "php": "^8.3",
    "ext-intl": "*",
    "waglpz/webapp-meta": "dev-master",
    "wikimedia/composer-merge-plugin": "^2.1"
  },
  "autoload": {
    "psr-4": {
      "@PROJECT_NS@\\": "src/"
    }
  },
  "autoload-dev": {
    "psr-4": {
      "@PROJECT_NS@\\Tests\\": "tests/"
    }
  },
  "replace": {
  },
  "scripts": {
    "post-install-cmd": [
      "cp -nR vendor/waglpz/di-container/config/* config/",
      "cp -nR vendor/waglpz/cli/config/* config/",
      "cp -nR vendor/waglpz/cli/migrations ./",
      "cp -nR vendor/waglpz/config/config/* config/",
      "cp -nR vendor/waglpz/webapp-routing/config/* config/",
      "cp -nR vendor/waglpz/webapp/public ./",
      "cp -nR vendor/waglpz/webapp/templates ./",
      "cp -nR vendor/waglpz/webapp/config/* config/",
      "cp -nR vendor/waglpz/webapp/migrations ./",
      "cp -nR vendor/waglpz/webapp-restapi/public ./",
      "cp -nR vendor/waglpz/webapp-restapi/templates ./",
      "cp -nR vendor/waglpz/webapp-restapi/swagger.json ./",
      "cp -nR vendor/waglpz/webapp-restapi/config/* config/",
      "cp -nR vendor/waglpz/webapp-security/config/* config/",
      "cp -nR vendor/waglpz/webapp-middleware/config/* config/"
    ],
    "post-update-cmd": [
      "cp -nR vendor/waglpz/di-container/config/* config/",
      "cp -nR vendor/waglpz/cli/config/* config/",
      "cp -nR vendor/waglpz/cli/migrations ./",
      "cp -nR vendor/waglpz/config/config/* config/",
      "cp -nR vendor/waglpz/webapp-routing/config/* config/",
      "cp -nR vendor/waglpz/webapp/public ./",
      "cp -nR vendor/waglpz/webapp/templates ./",
      "cp -nR vendor/waglpz/webapp/config/* config/",
      "cp -nR vendor/waglpz/webapp/migrations ./",
      "cp -nR vendor/waglpz/webapp-restapi/public ./",
      "cp -nR vendor/waglpz/webapp-restapi/templates ./",
      "cp -nR vendor/waglpz/webapp-restapi/swagger.json ./",
      "cp -nR vendor/waglpz/webapp-restapi/config/* config/",
      "cp -nR vendor/waglpz/webapp-security/config/* config/",
      "cp -nR vendor/waglpz/webapp-middleware/config/* config/"
    ]
  },
  "extra": {
    "ajgl-symlinks": {
      "swagger-api/swagger-ui": {
        "dist": "public/bundles/swagger-api"
      }
    },
    "merge-plugin": {
      "include": [
        "vendor/waglpz/webapp-meta/composer.json"
      ],
      "merge-dev": true,
      "merge-scripts": true,
      "replace": false,
      "recurse": true
    }
  }
}
